backend:
  name: github
  repo: andrepombo/andre-landing-astro
  branch: master
  base_url: https://auth.andrepombo.info
  auth_endpoint: /auth

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: articles
    label: Articles
    folder: src/content/articles
    create: true
    format: frontmatter
    extension: mdx
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Image URL, name: image, widget: image }
      - { label: Link (href), name: href, widget: string }
      - label: Tags
        name: tags
        widget: list
      - { label: Date, name: date, widget: datetime }
      - label: Body
        name: body
        widget: markdown
        required: false

  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    format: frontmatter
    extension: mdx
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Image URL, name: image, widget: image }
      - { label: Link (href), name: href, widget: string }
      - label: Tags
        name: tags
        widget: list
      - { label: Highlight, name: highlight, widget: string, required: false }
      - label: Body
        name: body
        widget: markdown
        required: false
